# core/schemas.py (V3.0 - The Craftsman's Mind)

from __future__ import annotations
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict
from typing_extensions import TypedDict
import numpy as np
from numpy.typing import NDArray
import uuid
from datetime import datetime, timezone

# --- Core Trace Schemas (Validated for completeness) ---
class ToolCall(BaseModel):
    name: str
    args: Dict[str, Any]
    result: Optional[str] = None

class Attempt(BaseModel):
    id: int
    plan: List[str]
    confidence_score: Optional[float] = None
    tool_calls: Optional[List[ToolCall]] = Field(default_factory=list)
    candidate: str
    scores: Dict[str, float]
    total: float

class Best(BaseModel):
    attempt_id: int
    candidate: str
    total: float

class Reflection(BaseModel):
    what_worked: str
    what_failed: str
    next_adjustment: str

class Summary(BaseModel):
    answer: str
    reasoning: str
    next_action: str

class ModelInfo(BaseModel):
    name: str
    quant: Optional[str] = None
    runtime: str
    temp: float
    model_config = ConfigDict(protected_namespaces=())

class Trace(BaseModel):
    trace_id: str
    query: str
    seed_id: str
    summary: Summary
    attempts: List[Attempt]
    best: Best
    reflection: Reflection
    artifacts: Optional[List[str]] = Field(default_factory=list)
    timestamp: str
    model_info: ModelInfo
    persona_id: Optional[str] = None
    sub_traces: Optional[List[Trace]] = None


# --- Schemas for the Omega Core V2 & Self-Evolution Engine ---

# NEW: The core data structure for a structured, conceptual thought.
class ThoughtState(BaseModel):
    """
    Implements 'Semantic Scaffolding'. Represents a single, structured
    conceptual thought with grammatical components.
    """
    agent: NDArray[np.float32] = Field(description="The H_vector for the entity performing the action (e.g., Aletheia).")
    action: NDArray[np.float32] = Field(description="The H_vector for the action to be taken (e.g., ANALYZE, FORMULATE).")
    object: Optional[NDArray[np.float32]] = Field(default=None, description="The optional H_vector for the object of the action (e.g., 'the user's query').")
    context: Optional[NDArray[np.float32]] = Field(default=None, description="The optional H_vector for the situational context.")

    class Config:
        arbitrary_types_allowed = True

class SelfModel(BaseModel):
    """
    Aletheia's formal model of its own capabilities, failures, and strategies.
    """
    capabilities: Dict[str, float] = Field(default_factory=dict)
    failure_modes: Dict[str, str] = Field(default_factory=dict)
    effective_strategies: Dict[str, str] = Field(default_factory=dict)
    statistics: Dict[str, Any] = Field(default_factory=dict)

class GraphState(TypedDict):
    """
    Represents the state of our cognitive graph, now upgraded for the Omega Craftsman.
    """
    # Core state
    query: str
    context: str
    
    # Social context
    social_context: Optional[Dict[str, float]]

    # Cognitive assets
    pathway: Optional[Dict[str, Any]]
    
    # NEW: The structured conceptual plan generated by the Omega Planner V2
    structured_plan: Optional[List[ThoughtState]]
    
    # The linguistic plan, decoded from the structured_plan
    linguistic_plan: Optional[List[str]]
    
    candidate_answer: Optional[str]
    scores: Optional[Dict[str, float]]
    
    # Meta-cognition and Self-Evolution state
    revision_history: List[str]
    self_model: Optional[SelfModel]

# --- Schemas for the Subconscious "Dream Engine" ---

class MetaTrace(BaseModel):
    meta_trace_id: str = Field(default_factory=lambda: f"meta_{uuid.uuid4()}")
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    insight_text: str
    source_trace_ids: List[str]
    tags: List[str] = Field(default_factory=list)

class DreamGraphState(TypedDict):
    self_model: SelfModel
    strategic_insights: List[Dict[str, Any]]
    new_statistics: Optional[Dict[str, Any]]
    new_hypotheses: Optional[List[str]]